server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2;

    server_name hs.hapless.xyz;

    ssl_certificate "/etc/nginx/ssl/hs/fullchain.cer";
    ssl_certificate_key "/etc/nginx/ssl/hs/hs.hapless.xyz.key";

    ssl_protocols TLSv1.2 TLSv1.3;

    server_tokens off;

# reject weird methods
    if ($request_method !~ ^(GET|POST|HEAD)$ ) {
        return 444;
    }

# kill common exploit probes
    location ~* ^/(vendor|cgi-bin|phpunit|\.env|wp-admin|wp-login|HNAP1|boaform) {
        return 444;
    }

# everything else
    location / {
        return 444;
    }

# allowed headscale routes
    location ~ ^(/|/key|/register|/machine) {
        include /etc/nginx/http.d/hs/proxy.conf;
    }
}
