map $uri $deny_request {
    default 0;
    "~* ^/(vendor|cgi-bin|phpunit|\.env|wp-admin|wp-login|HNAP1|boaform|xmlrpc\.php|wp-content|wp-includes)" 1;
}

map $request_method $deny_method {
    default 1;
    "~* ^(GET|POST|HEAD)$" 0;
}

map $http_user_agent $deny_ua {
    default 0;
    "~* (bot|crawler|scanner|curl|wget|python|perl|ruby|java|php)" 1;
    "~* (nikto|sqlmap|nmap|nessus|openvas)" 1;
}
#
#map $http_user_agent $is_allowed_ua {
#    default 0;
#    "Go-http-client/1.1" 1;
#    "Go-http-client/2.0" 1;
#}
#
# this is how compound logic is applied on nginx
#map "$deny_ua:$is_allowed_ua" $block_ua {
#    default 0;
#
#    # deny_ua=1 and allowed_ua=0
#    "1:0" 1;
#}
