server {
    listen 443 ssl;
    listen [::]:443 ssl;
    server_name $server_name;

    include /etc/nginx/bots.d/ddos.conf;
    include /etc/nginx/bots.d/blockbots.conf;

    include /etc/nginx/location.d/deny.conf;

    # if / is not a valid base we can just deny it
    location / {
        return 444;
    }
}
