include /etc/nginx/http.d/common/deny.conf;

server {
    listen 443 ssl;
    listen [::]:443 ssl;
    server_name $server_name;

    include /etc/nginx/http.d/common/security.conf;

    location / {
        return 444;
    }
}
