# caching for osm tile server
#proxy_cache_path  /var/lib/docker/volumes/osm-data/_data levels=2:2 keys_zone=openstreetmap-backend-cache:8m max_size=500000m inactive=1000d;

server {
    listen 443      ssl;
    listen [::]:443 ssl;
    server_name osm.hapless.xyz;

    ssl_certificate "/etc/nginx/ssl/chaincert.hapless.xyz.crt";
    ssl_certificate_key "/etc/nginx/ssl/chaincert.hapless.xyz.key";
    ssl_protocols TLSv1.2 TLSv1.3;

    location / {
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X_FORWARDED_PROTO http;
        proxy_set_header Host $http_host;
        proxy_cache openstreetmap-backend-cache;
        proxy_cache_valid  200 302  365d;
        proxy_cache_valid  404      1m;
        proxy_redirect off;

        if (!-f $request_filename) {
            proxy_pass http://127.0.0.1:2323;
            break;
        }
    }
    location /tile {
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X_FORWARDED_PROTO $scheme;
        proxy_set_header Host $http_host;
        proxy_pass http://127.0.0.1:2323/tile;  # Adjust path for tile server routing
    }
}
